### ISSUE TITLE
Error when sh build.sh

### ISSUE THREAD

**Issue by z19311** [Project-HAMi/HAMi-core#11]
Environment
Ubuntu 18.04 + CUDA 12.4

Error occurs when excuting **sh build.sh**

build.sh: 7: build.sh: [[: not found
build.sh: 11: build.sh: CMAKE_OPTIONS+= -DDLSYM_HOOK_ENABLE=1: not found
build.sh: 13: build.sh: CMAKE_OPTIONS+= -DMULTIPROCESS_LIMIT_ENABLE=1: not found
build.sh: 14: build.sh: CMAKE_OPTIONS+= -DHOOK_MEMINFO_ENABLE=1: not found
build.sh: 15: build.sh: CMAKE_OPTIONS+= -DHOOK_NVML_ENABLE=1: not found
build.sh: 16: build.sh: CMAKE_OPTIONS+= -DCMAKE_BUILD_TYPE=Debug: not found
CI_COMMIT_BRANCH:unknown
CI_COMMIT_SHA:fb11ec3d83318c4c7924c1675071d1cc778a7472
-- Git hash is fb11ec3
CMake Error at src/multiprocess/CMakeLists.txt:4 (target_link_libraries):
  Object library target "multiprocess_mod" may not link to anything.

-- Configuring incomplete, errors occurred!
See also "/home/HAMi-core/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

Could you show us the build environment?

**Comment by daiqizhi** [comment]
bash build.sh or chmod +x build.sh ; ./build.sh

**Comment by jiangxiaobin96** [comment]
> bash build.sh or chmod +x build.sh ; ./build.sh

Same problem. `bash build.sh or chmod +x build.sh ; ./build.sh` doesn't work.
